name: Go

on:
  push:
    paths:
      - "app/server/*"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      # working-directory: push.path
      run: echo $({push.paths})
      # run: go build -v ./...

    - name: Test
      run: go test -v ./...
